name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release (e.g., 1.0.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: go mod tidy

      - name: Create Bin Directory
        run: mkdir -p ./bin

      - name: Build for Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ github.event.inputs.version }}" -o ./bin/auth-${{ github.event.inputs.version }}-linux-amd64 ./cmd/server

      - name: Build for Linux (arm)
        run: |
          GOOS=linux GOARCH=arm go build -ldflags "-X main.version=${{ github.event.inputs.version }}" -o ./bin/auth-${{ github.event.inputs.version }}-linux-arm ./cmd/server

      - name: Build for Linux (x86)
        run: |
          GOOS=linux GOARCH=386 go build -ldflags "-X main.version=${{ github.event.inputs.version }}" -o ./bin/auth-${{ github.event.inputs.version }}-linux-x86 ./cmd/server

      - name: Build for Windows (amd64)
        run: |
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${{ github.event.inputs.version }}" -o ./bin/auth-${{ github.event.inputs.version }}.exe ./cmd/server

      - name: Get Commits Since Last Release
        id: get_commits
        run: |
          git fetch --prune --unshallow --tags
          
          if last_tag=$(git describe --tags --abbrev=0 --match="auth-v*"); then
            echo "Found tag: $last_tag"
          else
            last_tag="first_release"
            echo "No matching tag found. Setting last_tag to: $last_tag"
          fi
          
          if [ "$last_tag" != "first_release" ]; then
            COMMIT_MESSAGES=$(git log "$last_tag"..HEAD --pretty=format:"%h - %s")
          else
            COMMIT_MESSAGES=$(git log --pretty=format:"%h - %s")
          fi
          
          printf "COMMIT_MESSAGES<<EOF\n%s\nEOF\n" "$COMMIT_MESSAGES" >> $GITHUB_ENV

      - name: Tag the Release
        run: |
          git tag auth-v${{ github.event.inputs.version }}
          git push origin auth-v${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auth-v${{ github.event.inputs.version }}
          files: |
            ./bin/auth-${{ github.event.inputs.version }}-linux-amd64
            ./bin/auth-${{ github.event.inputs.version }}-linux-arm
            ./bin/auth-${{ github.event.inputs.version }}-linux-x86
            ./bin/auth-${{ github.event.inputs.version }}.exe
          body: |
            ## Changes since last release
            ${{ env.COMMIT_MESSAGES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
